apiVersion: v1
kind: Secret
metadata:
  name: bluemarble-secrets
  namespace: bluemarble
type: Opaque
data:
  # PASTE THE OUTPUTS FROM THE TERMINAL COMMANDS HERE:
  jwt-secret: eW91ci1zZWNyZXQta2V5  
  mongodb-root-password: cm9vdHBhc3N3b3Jk  